### ISSUE TITLE
Incorrect install path

### ISSUE THREAD

**Issue by abznt** [dokempf/cerberus-cpp#12]
Following the build instructions, the headers are being installed to `/usr/local/cerberus-cpp/include` instead of `/usr/local/include/cerberus-cpp` (which I'm assuming is the correct location). Even if the installed files are on my search path, including `validator.hh` into my project causes errors since it expects `cerberus-cpp/error.hh` to be in the search path instead of `cerberus-cpp/include/error.hh` (the actual install path)

This could be fixed by updating `cerberus-cpp/CMakeLists.txt` to:
```cmake
install(FILES error.hh
              rules.hh
              stack.hh
              types.hh
              validator.hh
        DESTINATION ${CMAKE_INSTALL_PREFIX}/include/cerberus-cpp/)
```

**Comment by dokempf** [comment]
Thanks for reporting. I have taken this a step further and modernized the entire CMake build system to also export a target. Could you give this a try?
